[profile.default]
src = "contracts/evm"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 120
tab_width = 4

[profile.ci]
src = "contracts/evm"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
fuzz = { runs = 256 }
invariant = { runs = 256 }

[rpc_endpoints]
ethereum = "${ETH_RPC_URL}"
bsc = "${BSC_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
linea = "${LINEA_RPC_URL}"
zksync = "${ZKSYNC_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
optimism = { key = "${OPSCAN_API_KEY}" }
avalanche = { key = "${SNOWTRACE_API_KEY}" }
linea = { key = "${LINEASCAN_API_KEY}" }
